### ISSUE TITLE
How to build Fraxinus

### ISSUE THREAD

**Issue by ekmungi** [SINTEFMedtek/Fraxinus#1]
I appreciate the effort put into both CustusX and its branches. 

I am having trouble building Fraxinus. I built CustusX without any problem. However with Fraxinus 

- It is not clear if the repository has be to cloned inside the CustusX directory OR separately? 
- Within the Fraxinus build environment, how can I link the python build package from CustusX to build environment of Fraxinus?

I was wondering if the developers could help me out with this. Thank you!

Anant.

**Comment by ekmungi** [comment]
I added the files from Fraxinus repo to CustusX source in the following manner.

Copied folder `org.custusx.fraxinus` to `source/apps/` (in CustusX)
Copied folders `org.custusx.fraxinus.core.state` & `org.custusx.fraxinus.widgets` to `source/plugins/` (in CustusX)

I selected the corresponding app and plugin from the cmake configuration, but I am unable to complete the build.

When I compile I get a few errors: 

`mMetricManager(new MetricManager(services->view(), services->patient(), services->tracking(), services->spaceProvider())),` ---> MetricManager class requires 5 parameters but received 4.

I modified it to:

`mMetricManager(new MetricManager(services->view(), services->patient(), services->tracking(), services->spaceProvider(), NULL)),`

This fixed the first problem.

However after this, I get the following error:
`source/plugins/org.custusx.filter.airways/cxAirwaysFilterService.h:28:10: fatal error: FAST/Importers/ImageFileImporter.hpp: No such file or directory`

I cannot figure out what is causing this error. When building the without Fraxinus I don't get this error. Could someone please help?

Anant.

**Comment by olevs** [comment]
Hi Anant,

I'm sorry for the lack of simple build instructions for Fraxinus.
The easiest way is to build it separately from CustusX, using the Python build script similar to the way CustusX is built. The build script will then download all the needed repositories:
`mkdir dev/fx`
`cd dev/fx`
`git clone git@github.com:SINTEFMedtek/Fraxinus.git Fraxinus/Fraxinus`
`cd Fraxinus/Fraxinus`
`git checkout develop`
`./script/cxFraxinusInstaller.py --all --full --build_type Release --user_doc`

Best,
Ole Vegard

**Comment by ekmungi** [comment]
Thanks Ole. I kind of tried that, but then the python script for installation is throwing errors that it cannot find the python files used as imports from the from the CustusX build. Do I need to add the python build script for CustusX to the path for building Fraxinus?

Anant.

**Comment by olevs** [comment]
No, manually adding the CustusX repo isn't needed, as the build script should download this on its own.
I'm guessing you used the master branch instead of the develop branch?
The master branch only works with Python 2, and will give such errors if you try to run it with Python 3. Make sure you switch to the develop branch before running the script: `git checkout develop`

**Comment by ekmungi** [comment]
Aha... You are correct, I was working on the master branch and switching develop solved the issue. Thank you.

However I am having issue with cloning medtekAI repo. I get the following error.

```
The authenticity of host 'git.code.sintef.no (78.91.101.54)' can't be established.
RSA key fingerprint is SHA256:iU0mTjdnIpMA+ZfMoyHrjFBTjENndAuI/2cRqbJQCqg.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'git.code.sintef.no,78.91.101.54' (RSA) to the list of known hosts.
git@git.code.sintef.no: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[shell info] Terminating: shell command exited with a nonzero return value [128]
Terminating: shell command exited with a nonzero return value [128]
```

**Comment by ekmungi** [comment]
I was able to fix the problem by commenting out the 

`script/cxsetup/cxPrivateComponentAssembly.py`

```
# self.addComponent(cxPrivateComponents.medtekAI())
```
But I am curious if this plugin is closed-source.

I am getting a weird crash when closing the  app. I am wondering if you could help with it.

```
[22:13:49.271][0]  --- Shutting down Fraxinus...
qSetGlobalQHashSeed: forced seed value is not 0, cannot guarantee that the hashing functions will produce a stable value.[22:13:49.283][0] Saved patient /home/data/Patients/Bronchoscopy/example_1.cx3
[22:13:49.313][0] Layout 0 changed to VB 3D ANY
[22:13:49.496][1] UsReconstructionImplService::selectData: Invalid input data
[22:13:49.575][0] Uninstalling tracking system: org.custusx.core.tracking.system.igstk
[22:13:49.576][0] Uninstalling tracking system: org.custusx.core.openigtlink3
[22:13:49.722][1] [QT] QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
terminate called after throwing an instance of 'ctkPluginDatabaseException'
  what():  ctkPluginDatabaseException: Problem closing database: Invalid connection plugins
zsh: abort (core dumped)  ./Fraxinus
```

**Comment by olevs** [comment]
Yes, medtekAI is a closed-source plugin, and your fix is the correct one.

Are you compiling this on Ubuntu 20.04 or similar? I have observed this kinds of issues there and will be looking into it.

**Comment by ekmungi** [comment]
Yes, I am on Ubuntu 20.04. Using gcc 7.5.0 if that's relevant.

**Comment by ekmungi** [comment]
Hi Ole, 

Perhaps this is a silly question, but I was wondering if you could share some information about how to configure the overall project with an IDE such as QtCreator or perhaps an alternative. I would like play around with the Fraxinus code and add additional functionalities.

In qtcreator I tried to add CMakeLists.txt from `./FX/org.custusx.fraxinus/` as the master project, but there are undefined macros such as 

`Unknown CMake command "cx_add_optional_app_subdirectory"`

Is it possible to configure the project with qtcreator or a similar such ide.

Would appreciate any insights you can offer. Thanks!

Anant.

**Comment by olevs** [comment]
Hi Anant,

I'm sorry if the setup may be a bit confusing, but Fraxinus should be set up the same way as CustusX in QtCreator: That means you use the CMakeLists.txt from the CX/CX folder in the Fraxinus directory.

Fraxinus is really just a modification of CustusX, and uses the same infrastructure.

Ole Vegard

**Comment by ekmungi** [comment]
Thank you Ole, That worked. Appreciate it. If however you figure out the cause of the crash 

```
terminate called after throwing an instance of 'ctkPluginDatabaseException'
  what():  ctkPluginDatabaseException: Problem closing database: Invalid connection plugins
```

please post the update. I will watch the repo for changes. Thank you!
