### ISSUE TITLE
Build instruction needed

### ISSUE THREAD

**Issue by shu-gong** [SINTEFMedtek/Fraxinus#3]
Hi developers,

I am new to open source software, and can anyone tell me how to build Fraxinus? 

What I have done:
Custusx -- Downloaded & Build 

What I want to know:
1. which **directory** should I use for Fraxinus? For example, my Custusx path is ~/dev/cx/CX/CX/, and I run ./install/cxInstaller.py --full --all --build_type Release --user_doc to install Custusx. 
2. what **command** should I type to install Fraxinus? 

My environment is: Ubuntu 16.04.

Thanks.

**Comment by olevs** [comment]
Hi,

We are sorry for the lack of build instructions for Fraxinus.

The easiest setup is to build it in a separate folder from the CustusX build, using the build script from the Fraxinus repository. Starting from scratch it should be something like this:
mkdir dev
mkdir dev/fx
cd dev/fx
git clone git@github.com:SINTEFMedTek/Fraxinus.git FX/FX
cd FX/FX
git checkout develop
./FX/FX/script/cxFraxinusInstaller.py --full --all -t Release

Best Regards,
Ole Vegard Solberg
